### ISSUE TITLE
CUDA error: invalid configuration argument

### ISSUE THREAD

**Issue by Yzichen** [Xharlie/BtcDet#3]
When I run multifindbestfit.py, It reports an error:  CUDA error: invalid configuration argument. How can I fix it ？

**Comment by Yzichen** [comment]
I increased the number of loops in the get_iou function, The problem is solved .

**Comment by laiyingxin2** [comment]
same question,I tried to change the for i in range(11): increase or decrease to 200, 12,1000 ,1......There are still mistakes,请问你是怎么更改的

**Comment by laiyingxin2** [comment]
def get_iou(box_tensor):
    limit = len(box_dims_lst)
    start = 0
    iou3d_lst = []
    for i in range(64):
        end = min(start + limit // 10, limit)
        iou3d = iou3d_nms_utils.boxes_iou3d_gpu(box_tensor[start:end, :], box_tensor)
        iou3d_lst.append(iou3d)
        start = end
    iou3d = torch.cat(iou3d_lst, dim=0)
    print("iou3d", iou3d.shape)
    return iou3d

in this function

**Comment by DheerajYarlagadda** [comment]
when I'm trying to increase the loops in the 'get_iou' function.
it is giving me an error 'CUDA error: invalid configuration argument'.
But when I set back the loop length to normal/original, I'm not getting this error.
Could you please let me know how you overcome this error?
